#!/bin/sh
if ERROR="$( { fusermount -u "$1"; } 2>&1 )"; then
    exit 0
else
    if [ "$ERROR" ]; then
	MSG="$ERROR"
    else
	MSG="Unknown error while unmounting."
    fi
    zenity --warning --text="$MSG"
    exit 1
fi
