#!/bin/sh
if ERROR="$( { fusermount -u "$1"; } 2>&1 )"; then
    exit 0
else
    [ "$ERROR" ] && MSG="$ERROR" || MSG="Unknown error while unmounting."
    zenity --warning --text="$MSG"
    exit 1
fi
