#!/bin/sh
MOUNTPOINT="$( zenity --file-selection \
    --title="Select mount point" --directory --filename="$HOME/media/" )"
if [ "$?" -ne 0 ]; then
    exit 1
fi
M="$( find "$MOUNTPOINT" -maxdepth 0 -type d -empty )"
if [ -z "$M" ]; then
    zenity --error --text="Error: $MOUNTPOINT is not an empty directory"
    exit 1
fi
if ERROR="$( { fuseiso "$1" "$MOUNTPOINT"; } 2>&1 )"; then
    exit 0
else
    if [ "$ERROR" ]; then
	MSG="$ERROR"
    else
	MSG="Unknown error while mounting $1 to $MOUNTPOINT"
    fi
    zenity --warning --text="$MSG"
    exit 1
fi
